name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  pipeline:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: flavioheartnet # name of Docker Hub ID
      IMAGE_NAME: suncoder
      IMAGE_TAG: ${{ github.run_number }} # $GITHUB_RUN_NUMBER

    steps:  
      - name: Checkout
        uses: actions/checkout@v4      
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - 
        name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0.3
        with:
          envkey_SUPABASE_URL: ${{secrets.NEXT_PUBLIC_SUPABASE_URL}}
          envkey_SUPABASE_SECRET_KEY: ${{secrets.SUPABASE_SECRET_KEY}}
          file_name: .env.local
          fail_on_empty: false
          sort_keys: false
      -
        name: Build 
        run:  docker build -t $DOCKER_REPOSITORY/$IMAGE_NAME:$GITHUB_RUN_NUMBER . 

      - name: Push Image to Docker Hub
        run: docker push $DOCKER_REPOSITORY/$IMAGE_NAME:$GITHUB_RUN_NUMBER
        
              

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with: 
          kustomize-version: "3.6.1"

      - name: Checkout new repo
        uses: actions/checkout@v4
        with: 
          path: 'suncoder-k8s'
          ref: 'master'
          repository: FlavioHeartnet/apps-k8s
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0


      - name: Update Kubernetes resources
        env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        run: |
          git clone https://github.com/FlavioHeartnet/apps-k8s.git
          cd apps-k8s/suncoder-k8s
          kustomize edit set image suncoder-app=$DOCKER_REPOSITORY/suncoder:$GITHUB_RUN_NUMBER
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Bump docker version" 
          git push -u https://github.com/FlavioHeartnet/apps-k8s.git master
        
