name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  pipeline:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: flavioheartnet # name of Docker Hub ID
      IMAGE_NAME: suncoder
      IMAGE_TAG: ${{ github.run_number }} # $GITHUB_RUN_NUMBER

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: $DOCKER_REPOSITORY/$IMAGE_NAME:$GITHUB_RUN_NUMBER 
        env: 
          SUPABASE_URL: ${{secrets.NEXT_PUBLIC_SUPABASE_URL}}
          SUPABASE_SECRET_KEY: ${{secrets.SUPABASE_SECRET_KEY}}
              

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with: 
          kustomize-version: "3.6.1"

      - name: Update Kubernetes resources
        env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        run: |
            git clone https://github.com/FlavioHeartnet/apps-k8s.git
            cd apps-k8s/suncoder-k8s
            kustomize edit set image suncoder-app=$DOCKER_REPOSITORY/suncoder:$GITHUB_RUN_NUMBER
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -am "Bump docker version" 
        
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: FlavioHeartnet/apps-k8s 
